name: app_name
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  encrypt: ^5.0.3
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  http: ^1.4.0
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  simple_router:
    git:
      url: https://github.com/n0dustoll3ns/simple_router.git
      ref: main


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
